[tool.poetry]
name = "prometheus_remediation"
version = "0.0.1"
description = ""
authors = ["Natan Yellin <aantn@users.noreply.github.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
